/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KsaShortAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KsaShortAddress{}

// KsaShortAddress struct for KsaShortAddress
type KsaShortAddress struct {
	ContactName string `json:"contact_name"`
	ContactPhone string `json:"contact_phone"`
	ShortAddress string `json:"short_address"`
	Instructions *string `json:"instructions,omitempty"`
}

type _KsaShortAddress KsaShortAddress

// NewKsaShortAddress instantiates a new KsaShortAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKsaShortAddress(contactName string, contactPhone string, shortAddress string) *KsaShortAddress {
	this := KsaShortAddress{}
	this.ContactName = contactName
	this.ContactPhone = contactPhone
	this.ShortAddress = shortAddress
	return &this
}

// NewKsaShortAddressWithDefaults instantiates a new KsaShortAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKsaShortAddressWithDefaults() *KsaShortAddress {
	this := KsaShortAddress{}
	return &this
}

// GetContactName returns the ContactName field value
func (o *KsaShortAddress) GetContactName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value
// and a boolean to check if the value has been set.
func (o *KsaShortAddress) GetContactNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactName, true
}

// SetContactName sets field value
func (o *KsaShortAddress) SetContactName(v string) {
	o.ContactName = v
}

// GetContactPhone returns the ContactPhone field value
func (o *KsaShortAddress) GetContactPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactPhone
}

// GetContactPhoneOk returns a tuple with the ContactPhone field value
// and a boolean to check if the value has been set.
func (o *KsaShortAddress) GetContactPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactPhone, true
}

// SetContactPhone sets field value
func (o *KsaShortAddress) SetContactPhone(v string) {
	o.ContactPhone = v
}

// GetShortAddress returns the ShortAddress field value
func (o *KsaShortAddress) GetShortAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShortAddress
}

// GetShortAddressOk returns a tuple with the ShortAddress field value
// and a boolean to check if the value has been set.
func (o *KsaShortAddress) GetShortAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShortAddress, true
}

// SetShortAddress sets field value
func (o *KsaShortAddress) SetShortAddress(v string) {
	o.ShortAddress = v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *KsaShortAddress) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KsaShortAddress) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *KsaShortAddress) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *KsaShortAddress) SetInstructions(v string) {
	o.Instructions = &v
}

func (o KsaShortAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KsaShortAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contact_name"] = o.ContactName
	toSerialize["contact_phone"] = o.ContactPhone
	toSerialize["short_address"] = o.ShortAddress
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	return toSerialize, nil
}

func (o *KsaShortAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contact_name",
		"contact_phone",
		"short_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKsaShortAddress := _KsaShortAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKsaShortAddress)

	if err != nil {
		return err
	}

	*o = KsaShortAddress(varKsaShortAddress)

	return err
}

type NullableKsaShortAddress struct {
	value *KsaShortAddress
	isSet bool
}

func (v NullableKsaShortAddress) Get() *KsaShortAddress {
	return v.value
}

func (v *NullableKsaShortAddress) Set(val *KsaShortAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableKsaShortAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableKsaShortAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKsaShortAddress(val *KsaShortAddress) *NullableKsaShortAddress {
	return &NullableKsaShortAddress{value: val, isSet: true}
}

func (v NullableKsaShortAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKsaShortAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


