/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
)

// checks if the DeliveryLogistics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryLogistics{}

// DeliveryLogistics struct for DeliveryLogistics
type DeliveryLogistics struct {
	// Meters.
	EstimatedDistance *float32 `json:"estimated_distance,omitempty"`
	// Seconds.
	EstimatedDuration *float32 `json:"estimated_duration,omitempty"`
	TrackingUrl *string `json:"tracking_url,omitempty"`
	PickupQrUrl *string `json:"pickup_qr_url,omitempty"`
}

// NewDeliveryLogistics instantiates a new DeliveryLogistics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryLogistics() *DeliveryLogistics {
	this := DeliveryLogistics{}
	return &this
}

// NewDeliveryLogisticsWithDefaults instantiates a new DeliveryLogistics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryLogisticsWithDefaults() *DeliveryLogistics {
	this := DeliveryLogistics{}
	return &this
}

// GetEstimatedDistance returns the EstimatedDistance field value if set, zero value otherwise.
func (o *DeliveryLogistics) GetEstimatedDistance() float32 {
	if o == nil || IsNil(o.EstimatedDistance) {
		var ret float32
		return ret
	}
	return *o.EstimatedDistance
}

// GetEstimatedDistanceOk returns a tuple with the EstimatedDistance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryLogistics) GetEstimatedDistanceOk() (*float32, bool) {
	if o == nil || IsNil(o.EstimatedDistance) {
		return nil, false
	}
	return o.EstimatedDistance, true
}

// HasEstimatedDistance returns a boolean if a field has been set.
func (o *DeliveryLogistics) HasEstimatedDistance() bool {
	if o != nil && !IsNil(o.EstimatedDistance) {
		return true
	}

	return false
}

// SetEstimatedDistance gets a reference to the given float32 and assigns it to the EstimatedDistance field.
func (o *DeliveryLogistics) SetEstimatedDistance(v float32) {
	o.EstimatedDistance = &v
}

// GetEstimatedDuration returns the EstimatedDuration field value if set, zero value otherwise.
func (o *DeliveryLogistics) GetEstimatedDuration() float32 {
	if o == nil || IsNil(o.EstimatedDuration) {
		var ret float32
		return ret
	}
	return *o.EstimatedDuration
}

// GetEstimatedDurationOk returns a tuple with the EstimatedDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryLogistics) GetEstimatedDurationOk() (*float32, bool) {
	if o == nil || IsNil(o.EstimatedDuration) {
		return nil, false
	}
	return o.EstimatedDuration, true
}

// HasEstimatedDuration returns a boolean if a field has been set.
func (o *DeliveryLogistics) HasEstimatedDuration() bool {
	if o != nil && !IsNil(o.EstimatedDuration) {
		return true
	}

	return false
}

// SetEstimatedDuration gets a reference to the given float32 and assigns it to the EstimatedDuration field.
func (o *DeliveryLogistics) SetEstimatedDuration(v float32) {
	o.EstimatedDuration = &v
}

// GetTrackingUrl returns the TrackingUrl field value if set, zero value otherwise.
func (o *DeliveryLogistics) GetTrackingUrl() string {
	if o == nil || IsNil(o.TrackingUrl) {
		var ret string
		return ret
	}
	return *o.TrackingUrl
}

// GetTrackingUrlOk returns a tuple with the TrackingUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryLogistics) GetTrackingUrlOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingUrl) {
		return nil, false
	}
	return o.TrackingUrl, true
}

// HasTrackingUrl returns a boolean if a field has been set.
func (o *DeliveryLogistics) HasTrackingUrl() bool {
	if o != nil && !IsNil(o.TrackingUrl) {
		return true
	}

	return false
}

// SetTrackingUrl gets a reference to the given string and assigns it to the TrackingUrl field.
func (o *DeliveryLogistics) SetTrackingUrl(v string) {
	o.TrackingUrl = &v
}

// GetPickupQrUrl returns the PickupQrUrl field value if set, zero value otherwise.
func (o *DeliveryLogistics) GetPickupQrUrl() string {
	if o == nil || IsNil(o.PickupQrUrl) {
		var ret string
		return ret
	}
	return *o.PickupQrUrl
}

// GetPickupQrUrlOk returns a tuple with the PickupQrUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryLogistics) GetPickupQrUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PickupQrUrl) {
		return nil, false
	}
	return o.PickupQrUrl, true
}

// HasPickupQrUrl returns a boolean if a field has been set.
func (o *DeliveryLogistics) HasPickupQrUrl() bool {
	if o != nil && !IsNil(o.PickupQrUrl) {
		return true
	}

	return false
}

// SetPickupQrUrl gets a reference to the given string and assigns it to the PickupQrUrl field.
func (o *DeliveryLogistics) SetPickupQrUrl(v string) {
	o.PickupQrUrl = &v
}

func (o DeliveryLogistics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryLogistics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EstimatedDistance) {
		toSerialize["estimated_distance"] = o.EstimatedDistance
	}
	if !IsNil(o.EstimatedDuration) {
		toSerialize["estimated_duration"] = o.EstimatedDuration
	}
	if !IsNil(o.TrackingUrl) {
		toSerialize["tracking_url"] = o.TrackingUrl
	}
	if !IsNil(o.PickupQrUrl) {
		toSerialize["pickup_qr_url"] = o.PickupQrUrl
	}
	return toSerialize, nil
}

type NullableDeliveryLogistics struct {
	value *DeliveryLogistics
	isSet bool
}

func (v NullableDeliveryLogistics) Get() *DeliveryLogistics {
	return v.value
}

func (v *NullableDeliveryLogistics) Set(val *DeliveryLogistics) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryLogistics) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryLogistics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryLogistics(val *DeliveryLogistics) *NullableDeliveryLogistics {
	return &NullableDeliveryLogistics{value: val, isSet: true}
}

func (v NullableDeliveryLogistics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryLogistics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


