/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
	"time"
)

// checks if the Delivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Delivery{}

// Delivery struct for Delivery
type Delivery struct {
	Status *string `json:"status,omitempty"`
	Code *string `json:"code,omitempty"`
	TestMode *bool `json:"test_mode,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Currency *string `json:"currency,omitempty"`
	DeliveryFee *float32 `json:"delivery_fee,omitempty"`
	Customer *DeliveryCustomer `json:"customer,omitempty"`
	Driver *DeliveryDriver `json:"driver,omitempty"`
	Logistics *DeliveryLogistics `json:"logistics,omitempty"`
}

// NewDelivery instantiates a new Delivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelivery() *Delivery {
	this := Delivery{}
	return &this
}

// NewDeliveryWithDefaults instantiates a new Delivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryWithDefaults() *Delivery {
	this := Delivery{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Delivery) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Delivery) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Delivery) SetStatus(v string) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Delivery) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Delivery) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *Delivery) SetCode(v string) {
	o.Code = &v
}

// GetTestMode returns the TestMode field value if set, zero value otherwise.
func (o *Delivery) GetTestMode() bool {
	if o == nil || IsNil(o.TestMode) {
		var ret bool
		return ret
	}
	return *o.TestMode
}

// GetTestModeOk returns a tuple with the TestMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetTestModeOk() (*bool, bool) {
	if o == nil || IsNil(o.TestMode) {
		return nil, false
	}
	return o.TestMode, true
}

// HasTestMode returns a boolean if a field has been set.
func (o *Delivery) HasTestMode() bool {
	if o != nil && !IsNil(o.TestMode) {
		return true
	}

	return false
}

// SetTestMode gets a reference to the given bool and assigns it to the TestMode field.
func (o *Delivery) SetTestMode(v bool) {
	o.TestMode = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *Delivery) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *Delivery) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *Delivery) SetAmount(v float32) {
	o.Amount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Delivery) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Delivery) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Delivery) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Delivery) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Delivery) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Delivery) SetCurrency(v string) {
	o.Currency = &v
}

// GetDeliveryFee returns the DeliveryFee field value if set, zero value otherwise.
func (o *Delivery) GetDeliveryFee() float32 {
	if o == nil || IsNil(o.DeliveryFee) {
		var ret float32
		return ret
	}
	return *o.DeliveryFee
}

// GetDeliveryFeeOk returns a tuple with the DeliveryFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetDeliveryFeeOk() (*float32, bool) {
	if o == nil || IsNil(o.DeliveryFee) {
		return nil, false
	}
	return o.DeliveryFee, true
}

// HasDeliveryFee returns a boolean if a field has been set.
func (o *Delivery) HasDeliveryFee() bool {
	if o != nil && !IsNil(o.DeliveryFee) {
		return true
	}

	return false
}

// SetDeliveryFee gets a reference to the given float32 and assigns it to the DeliveryFee field.
func (o *Delivery) SetDeliveryFee(v float32) {
	o.DeliveryFee = &v
}

// GetCustomer returns the Customer field value if set, zero value otherwise.
func (o *Delivery) GetCustomer() DeliveryCustomer {
	if o == nil || IsNil(o.Customer) {
		var ret DeliveryCustomer
		return ret
	}
	return *o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetCustomerOk() (*DeliveryCustomer, bool) {
	if o == nil || IsNil(o.Customer) {
		return nil, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *Delivery) HasCustomer() bool {
	if o != nil && !IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given DeliveryCustomer and assigns it to the Customer field.
func (o *Delivery) SetCustomer(v DeliveryCustomer) {
	o.Customer = &v
}

// GetDriver returns the Driver field value if set, zero value otherwise.
func (o *Delivery) GetDriver() DeliveryDriver {
	if o == nil || IsNil(o.Driver) {
		var ret DeliveryDriver
		return ret
	}
	return *o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetDriverOk() (*DeliveryDriver, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *Delivery) HasDriver() bool {
	if o != nil && !IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given DeliveryDriver and assigns it to the Driver field.
func (o *Delivery) SetDriver(v DeliveryDriver) {
	o.Driver = &v
}

// GetLogistics returns the Logistics field value if set, zero value otherwise.
func (o *Delivery) GetLogistics() DeliveryLogistics {
	if o == nil || IsNil(o.Logistics) {
		var ret DeliveryLogistics
		return ret
	}
	return *o.Logistics
}

// GetLogisticsOk returns a tuple with the Logistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delivery) GetLogisticsOk() (*DeliveryLogistics, bool) {
	if o == nil || IsNil(o.Logistics) {
		return nil, false
	}
	return o.Logistics, true
}

// HasLogistics returns a boolean if a field has been set.
func (o *Delivery) HasLogistics() bool {
	if o != nil && !IsNil(o.Logistics) {
		return true
	}

	return false
}

// SetLogistics gets a reference to the given DeliveryLogistics and assigns it to the Logistics field.
func (o *Delivery) SetLogistics(v DeliveryLogistics) {
	o.Logistics = &v
}

func (o Delivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Delivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.TestMode) {
		toSerialize["test_mode"] = o.TestMode
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.DeliveryFee) {
		toSerialize["delivery_fee"] = o.DeliveryFee
	}
	if !IsNil(o.Customer) {
		toSerialize["customer"] = o.Customer
	}
	if !IsNil(o.Driver) {
		toSerialize["driver"] = o.Driver
	}
	if !IsNil(o.Logistics) {
		toSerialize["logistics"] = o.Logistics
	}
	return toSerialize, nil
}

type NullableDelivery struct {
	value *Delivery
	isSet bool
}

func (v NullableDelivery) Get() *Delivery {
	return v.value
}

func (v *NullableDelivery) Set(val *Delivery) {
	v.value = val
	v.isSet = true
}

func (v NullableDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelivery(val *Delivery) *NullableDelivery {
	return &NullableDelivery{value: val, isSet: true}
}

func (v NullableDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


