/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KsaAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KsaAddress{}

// KsaAddress struct for KsaAddress
type KsaAddress struct {
	ContactName string `json:"contact_name"`
	ContactPhone string `json:"contact_phone"`
	City string `json:"city"`
	Street string `json:"street"`
	District string `json:"district"`
	Building string `json:"building"`
	Floor *string `json:"floor,omitempty"`
	Apartment *string `json:"apartment,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
}

type _KsaAddress KsaAddress

// NewKsaAddress instantiates a new KsaAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKsaAddress(contactName string, contactPhone string, city string, street string, district string, building string) *KsaAddress {
	this := KsaAddress{}
	this.ContactName = contactName
	this.ContactPhone = contactPhone
	this.City = city
	this.Street = street
	this.District = district
	this.Building = building
	return &this
}

// NewKsaAddressWithDefaults instantiates a new KsaAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKsaAddressWithDefaults() *KsaAddress {
	this := KsaAddress{}
	return &this
}

// GetContactName returns the ContactName field value
func (o *KsaAddress) GetContactName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactName
}

// GetContactNameOk returns a tuple with the ContactName field value
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetContactNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactName, true
}

// SetContactName sets field value
func (o *KsaAddress) SetContactName(v string) {
	o.ContactName = v
}

// GetContactPhone returns the ContactPhone field value
func (o *KsaAddress) GetContactPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactPhone
}

// GetContactPhoneOk returns a tuple with the ContactPhone field value
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetContactPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactPhone, true
}

// SetContactPhone sets field value
func (o *KsaAddress) SetContactPhone(v string) {
	o.ContactPhone = v
}

// GetCity returns the City field value
func (o *KsaAddress) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *KsaAddress) SetCity(v string) {
	o.City = v
}

// GetStreet returns the Street field value
func (o *KsaAddress) GetStreet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Street
}

// GetStreetOk returns a tuple with the Street field value
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetStreetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Street, true
}

// SetStreet sets field value
func (o *KsaAddress) SetStreet(v string) {
	o.Street = v
}

// GetDistrict returns the District field value
func (o *KsaAddress) GetDistrict() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.District
}

// GetDistrictOk returns a tuple with the District field value
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetDistrictOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.District, true
}

// SetDistrict sets field value
func (o *KsaAddress) SetDistrict(v string) {
	o.District = v
}

// GetBuilding returns the Building field value
func (o *KsaAddress) GetBuilding() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Building
}

// GetBuildingOk returns a tuple with the Building field value
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetBuildingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Building, true
}

// SetBuilding sets field value
func (o *KsaAddress) SetBuilding(v string) {
	o.Building = v
}

// GetFloor returns the Floor field value if set, zero value otherwise.
func (o *KsaAddress) GetFloor() string {
	if o == nil || IsNil(o.Floor) {
		var ret string
		return ret
	}
	return *o.Floor
}

// GetFloorOk returns a tuple with the Floor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetFloorOk() (*string, bool) {
	if o == nil || IsNil(o.Floor) {
		return nil, false
	}
	return o.Floor, true
}

// HasFloor returns a boolean if a field has been set.
func (o *KsaAddress) HasFloor() bool {
	if o != nil && !IsNil(o.Floor) {
		return true
	}

	return false
}

// SetFloor gets a reference to the given string and assigns it to the Floor field.
func (o *KsaAddress) SetFloor(v string) {
	o.Floor = &v
}

// GetApartment returns the Apartment field value if set, zero value otherwise.
func (o *KsaAddress) GetApartment() string {
	if o == nil || IsNil(o.Apartment) {
		var ret string
		return ret
	}
	return *o.Apartment
}

// GetApartmentOk returns a tuple with the Apartment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetApartmentOk() (*string, bool) {
	if o == nil || IsNil(o.Apartment) {
		return nil, false
	}
	return o.Apartment, true
}

// HasApartment returns a boolean if a field has been set.
func (o *KsaAddress) HasApartment() bool {
	if o != nil && !IsNil(o.Apartment) {
		return true
	}

	return false
}

// SetApartment gets a reference to the given string and assigns it to the Apartment field.
func (o *KsaAddress) SetApartment(v string) {
	o.Apartment = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *KsaAddress) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KsaAddress) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *KsaAddress) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *KsaAddress) SetInstructions(v string) {
	o.Instructions = &v
}

func (o KsaAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KsaAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contact_name"] = o.ContactName
	toSerialize["contact_phone"] = o.ContactPhone
	toSerialize["city"] = o.City
	toSerialize["street"] = o.Street
	toSerialize["district"] = o.District
	toSerialize["building"] = o.Building
	if !IsNil(o.Floor) {
		toSerialize["floor"] = o.Floor
	}
	if !IsNil(o.Apartment) {
		toSerialize["apartment"] = o.Apartment
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	return toSerialize, nil
}

func (o *KsaAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contact_name",
		"contact_phone",
		"city",
		"street",
		"district",
		"building",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKsaAddress := _KsaAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKsaAddress)

	if err != nil {
		return err
	}

	*o = KsaAddress(varKsaAddress)

	return err
}

type NullableKsaAddress struct {
	value *KsaAddress
	isSet bool
}

func (v NullableKsaAddress) Get() *KsaAddress {
	return v.value
}

func (v *NullableKsaAddress) Set(val *KsaAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableKsaAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableKsaAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKsaAddress(val *KsaAddress) *NullableKsaAddress {
	return &NullableKsaAddress{value: val, isSet: true}
}

func (v NullableKsaAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKsaAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


