/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DeliveryRequestDestination - struct for DeliveryRequestDestination
type DeliveryRequestDestination struct {
	KsaAddress *KsaAddress
	KsaShortAddress *KsaShortAddress
	KuwaitAddress *KuwaitAddress
	LocationAddress *LocationAddress
}

// KsaAddressAsDeliveryRequestDestination is a convenience function that returns KsaAddress wrapped in DeliveryRequestDestination
func KsaAddressAsDeliveryRequestDestination(v *KsaAddress) DeliveryRequestDestination {
	return DeliveryRequestDestination{
		KsaAddress: v,
	}
}

// KsaShortAddressAsDeliveryRequestDestination is a convenience function that returns KsaShortAddress wrapped in DeliveryRequestDestination
func KsaShortAddressAsDeliveryRequestDestination(v *KsaShortAddress) DeliveryRequestDestination {
	return DeliveryRequestDestination{
		KsaShortAddress: v,
	}
}

// KuwaitAddressAsDeliveryRequestDestination is a convenience function that returns KuwaitAddress wrapped in DeliveryRequestDestination
func KuwaitAddressAsDeliveryRequestDestination(v *KuwaitAddress) DeliveryRequestDestination {
	return DeliveryRequestDestination{
		KuwaitAddress: v,
	}
}

// LocationAddressAsDeliveryRequestDestination is a convenience function that returns LocationAddress wrapped in DeliveryRequestDestination
func LocationAddressAsDeliveryRequestDestination(v *LocationAddress) DeliveryRequestDestination {
	return DeliveryRequestDestination{
		LocationAddress: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DeliveryRequestDestination) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into KsaAddress
	err = newStrictDecoder(data).Decode(&dst.KsaAddress)
	if err == nil {
		jsonKsaAddress, _ := json.Marshal(dst.KsaAddress)
		if string(jsonKsaAddress) == "{}" { // empty struct
			dst.KsaAddress = nil
		} else {
			if err = validator.Validate(dst.KsaAddress); err != nil {
				dst.KsaAddress = nil
			} else {
				match++
			}
		}
	} else {
		dst.KsaAddress = nil
	}

	// try to unmarshal data into KsaShortAddress
	err = newStrictDecoder(data).Decode(&dst.KsaShortAddress)
	if err == nil {
		jsonKsaShortAddress, _ := json.Marshal(dst.KsaShortAddress)
		if string(jsonKsaShortAddress) == "{}" { // empty struct
			dst.KsaShortAddress = nil
		} else {
			if err = validator.Validate(dst.KsaShortAddress); err != nil {
				dst.KsaShortAddress = nil
			} else {
				match++
			}
		}
	} else {
		dst.KsaShortAddress = nil
	}

	// try to unmarshal data into KuwaitAddress
	err = newStrictDecoder(data).Decode(&dst.KuwaitAddress)
	if err == nil {
		jsonKuwaitAddress, _ := json.Marshal(dst.KuwaitAddress)
		if string(jsonKuwaitAddress) == "{}" { // empty struct
			dst.KuwaitAddress = nil
		} else {
			if err = validator.Validate(dst.KuwaitAddress); err != nil {
				dst.KuwaitAddress = nil
			} else {
				match++
			}
		}
	} else {
		dst.KuwaitAddress = nil
	}

	// try to unmarshal data into LocationAddress
	err = newStrictDecoder(data).Decode(&dst.LocationAddress)
	if err == nil {
		jsonLocationAddress, _ := json.Marshal(dst.LocationAddress)
		if string(jsonLocationAddress) == "{}" { // empty struct
			dst.LocationAddress = nil
		} else {
			if err = validator.Validate(dst.LocationAddress); err != nil {
				dst.LocationAddress = nil
			} else {
				match++
			}
		}
	} else {
		dst.LocationAddress = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.KsaAddress = nil
		dst.KsaShortAddress = nil
		dst.KuwaitAddress = nil
		dst.LocationAddress = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DeliveryRequestDestination)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DeliveryRequestDestination)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeliveryRequestDestination) MarshalJSON() ([]byte, error) {
	if src.KsaAddress != nil {
		return json.Marshal(&src.KsaAddress)
	}

	if src.KsaShortAddress != nil {
		return json.Marshal(&src.KsaShortAddress)
	}

	if src.KuwaitAddress != nil {
		return json.Marshal(&src.KuwaitAddress)
	}

	if src.LocationAddress != nil {
		return json.Marshal(&src.LocationAddress)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DeliveryRequestDestination) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.KsaAddress != nil {
		return obj.KsaAddress
	}

	if obj.KsaShortAddress != nil {
		return obj.KsaShortAddress
	}

	if obj.KuwaitAddress != nil {
		return obj.KuwaitAddress
	}

	if obj.LocationAddress != nil {
		return obj.LocationAddress
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DeliveryRequestDestination) GetActualInstanceValue() (interface{}) {
	if obj.KsaAddress != nil {
		return *obj.KsaAddress
	}

	if obj.KsaShortAddress != nil {
		return *obj.KsaShortAddress
	}

	if obj.KuwaitAddress != nil {
		return *obj.KuwaitAddress
	}

	if obj.LocationAddress != nil {
		return *obj.LocationAddress
	}

	// all schemas are nil
	return nil
}

type NullableDeliveryRequestDestination struct {
	value *DeliveryRequestDestination
	isSet bool
}

func (v NullableDeliveryRequestDestination) Get() *DeliveryRequestDestination {
	return v.value
}

func (v *NullableDeliveryRequestDestination) Set(val *DeliveryRequestDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryRequestDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryRequestDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryRequestDestination(val *DeliveryRequestDestination) *NullableDeliveryRequestDestination {
	return &NullableDeliveryRequestDestination{value: val, isSet: true}
}

func (v NullableDeliveryRequestDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryRequestDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


