/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
)

// checks if the BranchInputLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BranchInputLocation{}

// BranchInputLocation struct for BranchInputLocation
type BranchInputLocation struct {
	Lat *float32 `json:"lat,omitempty"`
	Lng *float32 `json:"lng,omitempty"`
}

// NewBranchInputLocation instantiates a new BranchInputLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBranchInputLocation() *BranchInputLocation {
	this := BranchInputLocation{}
	return &this
}

// NewBranchInputLocationWithDefaults instantiates a new BranchInputLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBranchInputLocationWithDefaults() *BranchInputLocation {
	this := BranchInputLocation{}
	return &this
}

// GetLat returns the Lat field value if set, zero value otherwise.
func (o *BranchInputLocation) GetLat() float32 {
	if o == nil || IsNil(o.Lat) {
		var ret float32
		return ret
	}
	return *o.Lat
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BranchInputLocation) GetLatOk() (*float32, bool) {
	if o == nil || IsNil(o.Lat) {
		return nil, false
	}
	return o.Lat, true
}

// HasLat returns a boolean if a field has been set.
func (o *BranchInputLocation) HasLat() bool {
	if o != nil && !IsNil(o.Lat) {
		return true
	}

	return false
}

// SetLat gets a reference to the given float32 and assigns it to the Lat field.
func (o *BranchInputLocation) SetLat(v float32) {
	o.Lat = &v
}

// GetLng returns the Lng field value if set, zero value otherwise.
func (o *BranchInputLocation) GetLng() float32 {
	if o == nil || IsNil(o.Lng) {
		var ret float32
		return ret
	}
	return *o.Lng
}

// GetLngOk returns a tuple with the Lng field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BranchInputLocation) GetLngOk() (*float32, bool) {
	if o == nil || IsNil(o.Lng) {
		return nil, false
	}
	return o.Lng, true
}

// HasLng returns a boolean if a field has been set.
func (o *BranchInputLocation) HasLng() bool {
	if o != nil && !IsNil(o.Lng) {
		return true
	}

	return false
}

// SetLng gets a reference to the given float32 and assigns it to the Lng field.
func (o *BranchInputLocation) SetLng(v float32) {
	o.Lng = &v
}

func (o BranchInputLocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BranchInputLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lat) {
		toSerialize["lat"] = o.Lat
	}
	if !IsNil(o.Lng) {
		toSerialize["lng"] = o.Lng
	}
	return toSerialize, nil
}

type NullableBranchInputLocation struct {
	value *BranchInputLocation
	isSet bool
}

func (v NullableBranchInputLocation) Get() *BranchInputLocation {
	return v.value
}

func (v *NullableBranchInputLocation) Set(val *BranchInputLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableBranchInputLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableBranchInputLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBranchInputLocation(val *BranchInputLocation) *NullableBranchInputLocation {
	return &NullableBranchInputLocation{value: val, isSet: true}
}

func (v NullableBranchInputLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBranchInputLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


