/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
)

// checks if the DeliveryCustomer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryCustomer{}

// DeliveryCustomer struct for DeliveryCustomer
type DeliveryCustomer struct {
	Name *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
	Latitude NullableFloat32 `json:"latitude,omitempty"`
	Longitude NullableFloat32 `json:"longitude,omitempty"`
}

// NewDeliveryCustomer instantiates a new DeliveryCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryCustomer() *DeliveryCustomer {
	this := DeliveryCustomer{}
	return &this
}

// NewDeliveryCustomerWithDefaults instantiates a new DeliveryCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryCustomerWithDefaults() *DeliveryCustomer {
	this := DeliveryCustomer{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeliveryCustomer) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryCustomer) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeliveryCustomer) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeliveryCustomer) SetName(v string) {
	o.Name = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *DeliveryCustomer) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryCustomer) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *DeliveryCustomer) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *DeliveryCustomer) SetPhone(v string) {
	o.Phone = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *DeliveryCustomer) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryCustomer) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *DeliveryCustomer) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *DeliveryCustomer) SetAddress(v string) {
	o.Address = &v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryCustomer) GetLatitude() float32 {
	if o == nil || IsNil(o.Latitude.Get()) {
		var ret float32
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryCustomer) GetLatitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *DeliveryCustomer) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableFloat32 and assigns it to the Latitude field.
func (o *DeliveryCustomer) SetLatitude(v float32) {
	o.Latitude.Set(&v)
}
// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *DeliveryCustomer) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *DeliveryCustomer) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryCustomer) GetLongitude() float32 {
	if o == nil || IsNil(o.Longitude.Get()) {
		var ret float32
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryCustomer) GetLongitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *DeliveryCustomer) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableFloat32 and assigns it to the Longitude field.
func (o *DeliveryCustomer) SetLongitude(v float32) {
	o.Longitude.Set(&v)
}
// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *DeliveryCustomer) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *DeliveryCustomer) UnsetLongitude() {
	o.Longitude.Unset()
}

func (o DeliveryCustomer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryCustomer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	return toSerialize, nil
}

type NullableDeliveryCustomer struct {
	value *DeliveryCustomer
	isSet bool
}

func (v NullableDeliveryCustomer) Get() *DeliveryCustomer {
	return v.value
}

func (v *NullableDeliveryCustomer) Set(val *DeliveryCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryCustomer(val *DeliveryCustomer) *NullableDeliveryCustomer {
	return &NullableDeliveryCustomer{value: val, isSet: true}
}

func (v NullableDeliveryCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


