/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BranchInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BranchInput{}

// BranchInput struct for BranchInput
type BranchInput struct {
	Name string `json:"name"`
	Phone string `json:"phone"`
	Address string `json:"address"`
	Location *BranchInputLocation `json:"location,omitempty"`
}

type _BranchInput BranchInput

// NewBranchInput instantiates a new BranchInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBranchInput(name string, phone string, address string) *BranchInput {
	this := BranchInput{}
	this.Name = name
	this.Phone = phone
	this.Address = address
	return &this
}

// NewBranchInputWithDefaults instantiates a new BranchInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBranchInputWithDefaults() *BranchInput {
	this := BranchInput{}
	return &this
}

// GetName returns the Name field value
func (o *BranchInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BranchInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BranchInput) SetName(v string) {
	o.Name = v
}

// GetPhone returns the Phone field value
func (o *BranchInput) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *BranchInput) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *BranchInput) SetPhone(v string) {
	o.Phone = v
}

// GetAddress returns the Address field value
func (o *BranchInput) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *BranchInput) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *BranchInput) SetAddress(v string) {
	o.Address = v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *BranchInput) GetLocation() BranchInputLocation {
	if o == nil || IsNil(o.Location) {
		var ret BranchInputLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BranchInput) GetLocationOk() (*BranchInputLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *BranchInput) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given BranchInputLocation and assigns it to the Location field.
func (o *BranchInput) SetLocation(v BranchInputLocation) {
	o.Location = &v
}

func (o BranchInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BranchInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["phone"] = o.Phone
	toSerialize["address"] = o.Address
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	return toSerialize, nil
}

func (o *BranchInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"phone",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBranchInput := _BranchInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBranchInput)

	if err != nil {
		return err
	}

	*o = BranchInput(varBranchInput)

	return err
}

type NullableBranchInput struct {
	value *BranchInput
	isSet bool
}

func (v NullableBranchInput) Get() *BranchInput {
	return v.value
}

func (v *NullableBranchInput) Set(val *BranchInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBranchInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBranchInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBranchInput(val *BranchInput) *NullableBranchInput {
	return &NullableBranchInput{value: val, isSet: true}
}

func (v NullableBranchInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBranchInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


