/*
Armada Automated Ordering API

The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 

API version: 2.0.0
Contact: support@armadadelivery.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package armadagen

import (
	"encoding/json"
)

// checks if the ListBranches200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBranches200Response{}

// ListBranches200Response struct for ListBranches200Response
type ListBranches200Response struct {
	Branches []Branch `json:"branches,omitempty"`
}

// NewListBranches200Response instantiates a new ListBranches200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBranches200Response() *ListBranches200Response {
	this := ListBranches200Response{}
	return &this
}

// NewListBranches200ResponseWithDefaults instantiates a new ListBranches200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBranches200ResponseWithDefaults() *ListBranches200Response {
	this := ListBranches200Response{}
	return &this
}

// GetBranches returns the Branches field value if set, zero value otherwise.
func (o *ListBranches200Response) GetBranches() []Branch {
	if o == nil || IsNil(o.Branches) {
		var ret []Branch
		return ret
	}
	return o.Branches
}

// GetBranchesOk returns a tuple with the Branches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBranches200Response) GetBranchesOk() ([]Branch, bool) {
	if o == nil || IsNil(o.Branches) {
		return nil, false
	}
	return o.Branches, true
}

// HasBranches returns a boolean if a field has been set.
func (o *ListBranches200Response) HasBranches() bool {
	if o != nil && !IsNil(o.Branches) {
		return true
	}

	return false
}

// SetBranches gets a reference to the given []Branch and assigns it to the Branches field.
func (o *ListBranches200Response) SetBranches(v []Branch) {
	o.Branches = v
}

func (o ListBranches200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBranches200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Branches) {
		toSerialize["branches"] = o.Branches
	}
	return toSerialize, nil
}

type NullableListBranches200Response struct {
	value *ListBranches200Response
	isSet bool
}

func (v NullableListBranches200Response) Get() *ListBranches200Response {
	return v.value
}

func (v *NullableListBranches200Response) Set(val *ListBranches200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListBranches200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListBranches200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBranches200Response(val *ListBranches200Response) *NullableListBranches200Response {
	return &NullableListBranches200Response{value: val, isSet: true}
}

func (v NullableListBranches200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBranches200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


